<?php

namespace Google\GeolocationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
    public function getCachedAddress($search, $options = array())
    {
        $qb = $this->createQueryBuilder('l')
                   ->select('l')
                   ->where('l.search = :search')
                   ->andWhere('l.options = :options')
                   ->setParameter('search', $search)
                   ->setParameter('options', json_encode($options))
                   ->setMaxResults(1);

        try {
            return $qb->getQuery()
                      ->getSingleResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            return null;
        }
    }

    public function cleanCache($expiresAt)
    {
        return $this->createQueryBuilder('l')
                    ->delete()
                    ->where('l.created < :expires')
                    ->setParameter('expires', $expiresAt)
                    ->getQuery()
                    ->execute();
    }
}
